### ISSUE TITLE
Search with name

### ISSUE THREAD

**Issue by zedxos** [Butterstroke/AniList-Node#18]
Is it possible that u can use name not ID?

**Comment by Butterstroke** [comment]
As far as I am aware, you cannot use a name with anime and manga queries for the API. Hence, why those methods only take IDs at the moment. That said, I have a feeling that might not be the case anymore since nearly every other query can use a name. I'll take a look into this and see if it is possible.

**Comment by Butterstroke** [comment]
Unfortunately, it doesn't look like you can do that with the API. So, likewise, the package will still allow you to only use an ID. 

That said, I recommend using the search method to look up anime/manga IDs by name and use those IDs for the anime and manga methods. It is probably the best workaround for your question.

**Comment by zedxos** [comment]
> Unfortunately, it doesn't look like you can do that with the API. So, likewise, the package will still allow you to only use an ID.
> 
> That said, I recommend using the search method to look up anime/manga IDs by name and use those IDs for the anime and manga methods. It is probably the best workaround for your question.

Thanks im gonna learn more about using cheerio and the api
